set ruler

" For all languages
set tabstop=4
set shiftwidth=4
set shiftround
set expandtab
set incsearch
set textwidth=0
set nocompatible
set backspace=2

" Syntax highlighting for all languages
syntax on

" Line numbers and coloring
set number
highlight LineNr ctermfg=Grey

" Always show open tabs at the top
set showtabline=2

" Highlight trailing whitespace
highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/

" Python
autocmd FileType python set textwidth=79

" HTML
autocmd FileType html set tabstop=2
autocmd FileType html set shiftwidth=2

" Vim
autocmd FileType vim set tabstop=2
autocmd FileType vim set shiftwidth=2

